apiVersion: 1

datasources:
  - name: MySQL
    uid: mysql-ds
    type: mysql
    access: proxy
    url: mysql:3306
    database: $MYSQL_DATABASE
    user: $MYSQL_USER
    isDefault: true
    editable: false
    secureJsonData:
      password: $MYSQL_PASSWORD
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
